[project]
name = "projeto-integrador"
version = "0.1.0"
description = "ETL Projeto integrador para tratamento e análise de dados"
authors = [
    {name = "msantstd",email = "marcios.020@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pandas (>=3.0.3,<4.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
